name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      - name: Build Presentation project
        run: dotnet build StudentEfCoreDemo.Presentation/StudentEfCoreDemo.Presentation/StudentEfCoreDemo.Presentation.csproj --restore

      - name: Build Domain project
        run: dotnet build StudentEfCoreDemo.Domain/StudentEfCoreDemo.Domain.csproj --restore

      - name: Build Infrastructure project
        run: dotnet build StudentEfCoreDemo.Infrastructure/StudentEfCoreDemo.Infrastructure.csproj --restore

      - name: Build Application project
        run: dotnet build StudentEfCoreDemo.Application/StudentEfCoreDemo.Application.csproj --restore

      - name: Build Tests project
        run: dotnet build StudentEfCoreDemo.Tests/StudentEfCoreDemo.Tests.csproj --restore

      - name: Run tests
        run: dotnet test StudentEfCoreDemo.Tests/StudentEfCoreDemo.Tests.csproj --no-build --verbosity normal